import CustomButton from './CustomButton/CustomButton'
import Separator from './Separator/Separator'
import { Normalize } from './Normalize/Normalize'
import CustomBackground from './modals/CustomBackground'
import CustomBackdrop from './modals/CustomBackdrop'
import OTPInputField from './OTP/OTPInputField'
import HeartLike from './HeartLike'
import Ticker from './Ticker'
import SimpleSwitch from './SimpleSwitch'
import TimePicker from './TimePicker'
import CheckBox from './CheckBox'
export { CustomButton, Separator, Normalize, CustomBackdrop, CustomBackground, OTPInputField,HeartLike, Ticker,SimpleSwitch, TimePicker, CheckBox }
